spring.application.name=spring-vulnerable-lab
server.port=8081

spring.security.token.secret=oZTLtwaTLc5NhDMe7ySI/4qvRS2UKlDfVQld4JArZeo=
spring.security.token.expiration=86400000

spring.profiles.active=dev